import resolve from '@rollup/plugin-node-resolve'
import babel from '@rollup/plugin-babel'

export default {
  input: 'src/public/assets/js/src/index.js',
  output: {
    file: 'src/public/assets/js/integration.js',
    format: 'cjs',
    banner: `/**
THIS FILE WAS GENERATED BY A BUILD AND SHOULD NOT BE EDITED DIRECTLY.
This file is the bundled integration code generated by running npm run build command in the command line.
To edit the integration code, please edit code in the src/ folder and run \`npm run build\` in the command line to regenerate this file.
**/
`
  },
  plugins: [
    resolve(),
    babel({ babelHelpers: 'bundled', presets: [['@babel/preset-env', { modules: false }]] })
  ]
}
